version: '3.8'

services:
  mysql-service:
    image: mysql:latest
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: security_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongolia
      - MONGO_INITDB_ROOT_PASSWORD=247balo

networks:
  default:
    name: docker_net_mongo

volumes:
  data: {}




